### ISSUE TITLE
Compiling throws error

### ISSUE THREAD

**Issue by ghost** [themasch/kftp#1]
Hello please fix this as I my team wants to use this.
# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x08083d77, pid=3700, tid=2896
# 
# Problematic frame:
# V  [cSocket.c+0x83d77]

Stack: [0x00040000,0x00080000),  sp=0x0007f9f8,  free space=254k
Native frames: (C=native code)
C  [cSockat.c+0x1047]          <========= C/native frame
C  ~StubRoutines::call_stub
C  [kernel32.dll+0x214c7]

**Comment by themasch** [comment]
I'm sure your team doesn't need this because this doesn't do anything at all. It was a school group project eight years ago and is just hosted here to share it with old group members. 

TL;DR: wontfix

**Comment by ghost** [comment]
Hi your fix dont work. Please reconsider. We still need this to work
